name: My First GitHub Actions

on:
  push:

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - name: Say Hello
        run: echo "Hello GitHub Actions"
      
      - name: Show OS
        run: uname -a 

      - name: Show current directory
        run: pwd

      - name: List files
        run: ls -la